name: nyt_news
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  # Functional programming
  dartz: ^0.10.0-nullsafety.2
  # Value equality
  equatable: ^2.0.2
  # Bloc for state management
  flutter_bloc: ^7.0.1
  # Dependency injection
  get_it: ^7.1.3
  # Remote API
  http: ^0.13.3
  # Path provider
  path_provider: ^2.0.2
  schttp: ^3.2.1
  # Sqlite
  sqflite: ^2.0.0+3
  # Open link
  url_launcher: ^6.0.3
  # Localization
  intl: ^0.17.0
  # Theme
  adaptive_theme: ^2.2.0
  # Env file
  flutter_dotenv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
flutter_intl:
  enabled: true
