name: nyt_news
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # Value equality
  equatable: ^1.2.0
  # Bloc for state management
  flutter_bloc: ^4.0.1
  # Functional programming
  dartz: ^0.8.6
  # Remote API
  http: ^0.12.0+4
  # Open link
  url_launcher: ^5.4.11
  # Sqlite
  sqflite: ^1.3.0
  # Path provider
  path_provider: ^1.6.11
  # Dependency injection
  get_it: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
